/**
 * Machine-readable error codes for the task validation pipeline.
 * Agents use these codes to programmatically handle and fix validation failures.
 */

const ERROR_CODES = {
  MISSING_REQUIRED: 'MISSING_REQUIRED',
  INVALID_TYPE: 'INVALID_TYPE',
  INVALID_VALUE: 'INVALID_VALUE',
  BELOW_MINIMUM: 'BELOW_MINIMUM',
  ABOVE_MAXIMUM: 'ABOVE_MAXIMUM',
  STRING_TOO_SHORT: 'STRING_TOO_SHORT',
  STRING_TOO_LONG: 'STRING_TOO_LONG',
  ARRAY_TOO_FEW: 'ARRAY_TOO_FEW',
  INVALID_TASK_TYPE: 'INVALID_TASK_TYPE',
  INVALID_DATETIME: 'INVALID_DATETIME',
  PII_DETECTED: 'PII_DETECTED',
  PROHIBITED_CONTENT: 'PROHIBITED_CONTENT',
  ILLEGAL_ACTIVITY: 'ILLEGAL_ACTIVITY',
  BUDGET_BELOW_MINIMUM: 'BUDGET_BELOW_MINIMUM',
  DURATION_EXCEEDS_MAX: 'DURATION_EXCEEDS_MAX',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  UNKNOWN_FIELD: 'UNKNOWN_FIELD',
};

module.exports = ERROR_CODES;
