/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans:    ['Satoshi', 'system-ui', '-apple-system', 'Segoe UI', 'Roboto', 'Helvetica Neue', 'Arial', 'sans-serif'],
        mono:    ['"JetBrains Mono"', 'monospace'],
      },
      colors: {
        // v17 design tokens
        bg:           '#FDF6EE',
        surface:      '#FFFFFF',
        ink:          '#1A1A1A',
        ink2:         '#8C8580',
        ink3:         '#A69E98',
        orange:       '#E8764B',
        'orange-bg':  '#FDEEE7',
        'orange-glo': 'rgba(232,118,75,0.18)',
        'orange-soft':'#E8764B',
        green:        '#2D7A3A',
        'green-bg':   'rgba(45,122,58,0.09)',
        'green-border':'rgba(45,122,58,0.18)',
        purple:       '#6D4FC2',
        'purple-bg':  'rgba(109,79,194,0.09)',
        'purple-border':'rgba(109,79,194,0.18)',
        red:          '#D44B4B',
        'red-bg':     'rgba(212,75,75,0.08)',
        gold:         '#D4963F',
        'gold-bg':    'rgba(212,150,63,0.08)',
        // Legacy tokens (kept for backward compat)
        bg: {
          DEFAULT:   '#FDF6EE',
          primary:   '#FDF6EE',
          secondary: '#FFFFFF',
          tertiary:  '#F5EFE7',
          dark:      '#1A1A1A',
        },
        text: {
          primary:        '#1A1A1A',
          secondary:      '#8C8580',
          tertiary:       '#8C8580',
          muted:          '#A69E98',
          subtle:         '#B8B2AD',
          'on-dark':      '#DDDDDD',
          'on-dark-muted':'#666666',
        },
        accent: {
          orange:       '#E8764B',
          'orange-light':'#FDEEE7',
          'orange-hover':'#D4683F',
        },
        status: {
          green:        '#2D7A3A',
          'green-light':'rgba(45,122,58,0.09)',
          red:          '#D44B4B',
          yellow:       '#D4963F',
          blue:         '#3B82F6',
        },
        border: {
          light:  '#F0EAE2',
          subtle: '#F0EAE2',
          input:  '#E8E0D8',
        },
        divider:          '#EBE4DC',
        cream:            '#FDF6EE',
        page:             '#FDF6EE',
        'border-default': '#E8E0D8',
        success:          '#2D7A3A',
        'success-light':  'rgba(45,122,58,0.09)',
        warning:          '#D4963F',
        'warning-light':  'rgba(212,150,63,0.08)',
        error:            '#D44B4B',
        'error-light':    'rgba(212,75,75,0.08)',
        info:             '#2563EB',
        'info-light':     '#EFF6FF',
        gold:             '#D4963F',
        'gold-light':     'rgba(212,150,63,0.08)',
        teal: {
          DEFAULT: '#E8764B',
          dark:    '#D4683F',
          light:   '#FDEEE7',
        },
        coral: {
          DEFAULT: '#E8764B',
          dark:    '#D4683F',
          light:   '#FDEEE7',
        },
      },
      borderRadius: {
        DEFAULT: '16px',
        sm:      '10px',
        full:    '9999px',
        card:    '16px',
        button:  '12px',
        badge:   '9999px',
        input:   '12px',
        tooltip: '10px',
        pill:    '9999px',
      },
      borderColor: {
        DEFAULT: '#E8E0D8',
        md:      '#DDD5CC',
      },
      boxShadow: {
        sm:      '0 1px 3px rgba(0,0,0,0.04)',
        card:    '0 1px 3px rgba(0,0,0,0.04)',
        lg:      '0 4px 12px rgba(0,0,0,0.06)',
        cta:     'none',
        'v4-sm': '0 1px 3px rgba(0,0,0,0.04)',
        'v4-md': '0 1px 3px rgba(0,0,0,0.04)',
        'v4-lg': '0 4px 12px rgba(0,0,0,0.06)',
        'v4-xl': '0 4px 12px rgba(0,0,0,0.06)',
      },
      fontSize: {
        'page-title':           ['28px', { lineHeight: '1.08', fontWeight: '800', letterSpacing: '-0.03em' }],
        'page-title-mobile':    ['22px', { lineHeight: '1.08', fontWeight: '800', letterSpacing: '-0.03em' }],
        'section-heading':      ['22px', { lineHeight: '1.3', fontWeight: '700', letterSpacing: '-0.02em' }],
        'section-heading-mobile':['18px', { lineHeight: '1.3', fontWeight: '700', letterSpacing: '-0.02em' }],
        'card-title':           ['15px', { lineHeight: '1.4', fontWeight: '600', letterSpacing: '-0.01em' }],
        'card-title-mobile':    ['15px', { lineHeight: '1.4', fontWeight: '600', letterSpacing: '-0.01em' }],
        body:                   ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-sm':              ['13px', { lineHeight: '1.5', fontWeight: '400' }],
        label:                  ['11px', { lineHeight: '1.4', fontWeight: '600', letterSpacing: '0.02em' }],
        tag:                    ['10px', { lineHeight: '1.4', fontWeight: '700', letterSpacing: '0.01em' }],
        'upper-label':          ['11px', { lineHeight: '1.4', fontWeight: '600', letterSpacing: '0.08em' }],
        'stat-number':          ['24px', { lineHeight: '1.2', fontWeight: '700' }],
        'stat-number-mobile':   ['20px', { lineHeight: '1.2', fontWeight: '700' }],
        'stat-label':           ['12px', { lineHeight: '1.4', fontWeight: '400' }],
        'nav-tab':              ['13px', { lineHeight: '1.4', fontWeight: '500' }],
        'bottom-nav':           ['10px', { lineHeight: '1.2', fontWeight: '500' }],
      },
      screens: {
        'xs': '375px',
      },
    },
  },
  plugins: [],
}
