/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans:    ['Sora', 'sans-serif'],
        mono:    ['"JetBrains Mono"', 'monospace'],
        courier: ['"Courier Prime"', 'monospace'],
        // Legacy aliases kept for backward compat
        'dm-mono': ['"JetBrains Mono"', 'monospace'],
      },
      colors: {
        // v9 design tokens
        bg:           '#F7F5F2',
        surface:      '#FFFFFF',
        ink:          '#111010',
        ink2:         'rgba(17,16,16,0.46)',
        ink3:         'rgba(17,16,16,0.26)',
        orange:       '#E8703D',
        'orange-bg':  '#FEF1EA',
        'orange-glo': 'rgba(232,112,61,0.18)',
        green:        '#16A071',
        'green-bg':   'rgba(22,160,113,0.08)',
        purple:       '#6B4FBF',
        'purple-bg':  'rgba(107,79,191,0.08)',
        // Legacy tokens (kept for backward compat)
        bg: {
          primary:   '#F7F5F2',
          secondary: '#FFFFFF',
          tertiary:  '#F0EDE8',
          dark:      '#111010',
        },
        text: {
          primary:        '#111010',
          secondary:      '#333333',
          tertiary:       'rgba(17,16,16,0.46)',
          muted:          'rgba(17,16,16,0.26)',
          subtle:         'rgba(17,16,16,0.2)',
          'on-dark':      '#DDDDDD',
          'on-dark-muted':'#666666',
        },
        accent: {
          orange:       '#E8703D',
          'orange-light':'#FEF1EA',
          'orange-hover':'#D4622E',
        },
        status: {
          green:        '#16A071',
          'green-light':'rgba(22,160,113,0.08)',
          red:          '#DC2626',
          yellow:       '#FEBC2E',
          blue:         '#3B82F6',
        },
        border: {
          light:  'rgba(0,0,0,0.06)',
          subtle: 'rgba(0,0,0,0.04)',
          input:  'rgba(0,0,0,0.10)',
        },
        divider:          '#EDE9E3',
        cream:            '#F7F5F2',
        page:             '#F7F5F2',
        'border-default': 'rgba(0,0,0,0.06)',
        success:          '#16A071',
        'success-light':  'rgba(22,160,113,0.08)',
        warning:          '#FEBC2E',
        'warning-light':  '#FEFCE8',
        error:            '#DC2626',
        'error-light':    '#FEF2F2',
        info:             '#2563EB',
        'info-light':     '#EFF6FF',
        gold:             '#D4A017',
        'gold-light':     '#FEF9E7',
        teal: {
          DEFAULT: '#E8703D',
          dark:    '#D4622E',
          light:   '#FEF1EA',
        },
        coral: {
          DEFAULT: '#E8703D',
          dark:    '#D4622E',
          light:   '#FEF1EA',
        },
      },
      borderRadius: {
        DEFAULT: '16px',
        sm:      '10px',
        full:    '9999px',
        card:    '16px',
        button:  '10px',
        badge:   '20px',
        input:   '10px',
        tooltip: '12px',
      },
      borderColor: {
        DEFAULT: 'rgba(0,0,0,0.06)',
        md:      'rgba(0,0,0,0.10)',
      },
      boxShadow: {
        sm:      '0 1px 3px rgba(0,0,0,0.04)',
        card:    '0 1px 0 rgba(255,255,255,0.8) inset, 0 1px 3px rgba(0,0,0,0.04)',
        lg:      '0 4px 20px rgba(0,0,0,0.08)',
        'v4-sm': '0 1px 3px rgba(0,0,0,0.04)',
        'v4-md': '0 1px 4px rgba(0,0,0,0.02), 0 8px 40px rgba(0,0,0,0.035)',
        'v4-lg': '0 4px 20px rgba(0,0,0,0.08)',
        'v4-xl': '0 16px 48px rgba(0,0,0,0.1)',
      },
      fontSize: {
        'page-title':           ['28px', { lineHeight: '1.2', fontWeight: '700', letterSpacing: '-0.02em' }],
        'page-title-mobile':    ['22px', { lineHeight: '1.2', fontWeight: '600', letterSpacing: '-0.02em' }],
        'section-heading':      ['22px', { lineHeight: '1.3', fontWeight: '700', letterSpacing: '-0.02em' }],
        'section-heading-mobile':['18px', { lineHeight: '1.3', fontWeight: '600', letterSpacing: '-0.01em' }],
        'card-title':           ['15px', { lineHeight: '1.4', fontWeight: '700', letterSpacing: '-0.01em' }],
        'card-title-mobile':    ['15px', { lineHeight: '1.4', fontWeight: '500', letterSpacing: '-0.01em' }],
        body:                   ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-sm':              ['13px', { lineHeight: '1.5', fontWeight: '400' }],
        label:                  ['11px', { lineHeight: '1.4', fontWeight: '600', letterSpacing: '0.02em' }],
        tag:                    ['10px', { lineHeight: '1.4', fontWeight: '700', letterSpacing: '0.01em' }],
        'upper-label':          ['10px', { lineHeight: '1.4', fontWeight: '600', letterSpacing: '0.12em' }],
        'stat-number':          ['24px', { lineHeight: '1.2', fontWeight: '700' }],
        'stat-number-mobile':   ['20px', { lineHeight: '1.2', fontWeight: '700' }],
        'stat-label':           ['12px', { lineHeight: '1.4', fontWeight: '400' }],
        'nav-tab':              ['13px', { lineHeight: '1.4', fontWeight: '500' }],
        'bottom-nav':           ['10px', { lineHeight: '1.2', fontWeight: '500' }],
      },
      screens: {
        'xs': '375px',
      },
    },
  },
  plugins: [],
}
